spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/student_scoring_db
    username: ${DB_USER:student_user}
    password: ${DB_PASSWORD:student_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      leak-detection-threshold: 60000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    com.studentscoring: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE